### PR TITLE
use variables instead of hard code

### PR DESCRIPTION
**Pull request by widewing**

### CODE REVIEW

**Comment by samtap** [comment]
I prefer to not make this configurable to keep things simple. But maybe you can explain what problem is being solved and convince me? ;-)

**Comment by widewing** [comment]
I want to use nfs to extend the storage, so in this case a

**Comment by widewing** [comment]
I want to use nfs and want to but it without sdcard, so in this case the configurable network settings are necessary . Beside, the default config are already defined, so I don't think it will have access impact

**Comment by widewing** [comment]
Sorry for the typos,I typed in a mobile phone...

**Comment by samtap** [comment]
I think you have bigger problems, such as the network script being on the sdcard. Classical chicken/egg problem...
I feel the following options would be more valuable, for others as well:
- Make it actually boot from NFS by modifying kernel cmdline from u-boot. Should be quite straightforward, only potential issue is getting u-boot to use the wifi device...
- Make a option in the webif to 'deploy' in stand-alone mode, that would copy i.e. the rtsp server executable + some scripts, to the device flash.

**Comment by widewing** [comment]
Modifying cmdline is too risky for me, and the internal storage is not enough for the whole hack. What I intend to do is to defer the loading of the daemons(ssh, rtsp, etc.), to run these script only after network is connected and nfs mounted. I think in this way I need only a little modification, like to inject the network script, and modify rc.local

**Comment by samtap** [comment]
If you make it robust and optional I'd be happy to take a PR but it has to be a completed feature. 
I would try to get it done in fang_hacks.sh and leave rc.local untouched. You can find some traces of $HACKS_HOME (it's not used consistently) as I initially also wanted to make the location configurable. 
You could add a config option to fang_hacks.cfg to set 'standalone' mode. When that is set, in fang_hacks skip the sd mounting but instead bring up wifi, mount nfs and set HACKS_HOME accordingly. Then most of the other stuff in the scripts should work as-is. You'll have to check all the cgi scripts for proper use of HACKS_HOME as well and get rid of any hardcoded paths.
Now that I think of it, the dropbear build has some dirty hacks as well, to make it work from sd-card :-(. I remember changing the sftp-server location and I also did some stuff to make it source a profile file (that sets up proper library/path variables for using binaries off sdcard).

**Comment by widewing** [comment]
Ok let me do more research on this first. This PR closed.

**Pull request closed without merging**
