### PR TITLE
Create 99-rtsp-check

### PR DESCRIPTION
**Pull request by ant-thomas**
Simple bash loop to check if snx_rtsp_server is running - if not it will start it again.

### CODE REVIEW

**Comment by samtap** [comment]
I appreciate the pull request, but I'm looking into a different rtsp server and I'll probably not release any more images until I can include it. 

Also, the current rtsp server has been running stable for me. Perhaps it is worth investigating why it crashes? I can provide a debug build if anyone is interested.

If there's an issue that causes the rtsp server to crash, I believe the device should be rebooted. The rtsp server code is pretty rough and I've seen it crash often during termination. Also someone reported the device became very slow after a crash, so a reboot it probably the best option. Instead of creating a seperate '99-rtsp-check' script I would prefer if all of this is handled by the 20-rtsp-server script itself.

If you want others to benefit from this I invite you to create a wiki page, by including instructions on how to add/replace script files on the device etc. it'll be helpful to anyone who installed the image (most users by far).

**Comment by gonzonick** [comment]
I'll run the debug build if you want. My camera originally had rtsp crash a lot, but now it has been stable for at least two weeks, no changes, so who knows? I also got a second camera that I hope to get online today so I can compare the two as well.

**Comment by ant-thomas** [comment]
Thanks for the response. I didn't think it would be an ideal solution so if you are already working on a better rtsp server then that is even better news. More than happy to help out where I can.

**Comment by eran-** [comment]
If any solution similar to this is going to be ever implemented, I would suggest editing `20-rtsp-server start` to create a PID file (a file that contains the PID of the created service) and have the periodic validation validate against the PID instead of the process name.

**Pull request closed without merging**
